{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: malware-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: malware-analyzer
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
