apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: mijil
data:
  config.yml: |
    # Thay thế <TUNNEL-UUID> bằng id của tunnel từ tệp JSON thông tin xác thực.
    tunnel: <TUNNEL-UUID>
    credentials-file: /etc/cloudflared/credentials.json
    ingress:
      - hostname: note-audio-registry-scoring.trycloudflare.com
        service: http://frontend-service.mijil.svc.cluster.local:80
      - service: http_status:404
