apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mijil-ingress
  namespace: mijil
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`mijil.local`) || PathPrefix(`/`)
    kind: Rule
    services:
    - name: frontend-service
      port: 80
  - match: Host(`mijil.local`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: backend-service
      port: 8080
